# Generated by Django 5.0.2 on 2024-02-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Email', models.EmailField(max_length=300, unique=True)),
                ('Password', models.CharField(max_length=100, unique=True)),
                ('Confirmpass', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
