# Generated by Django 5.0.2 on 2024-02-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_confirmpass_register_confirmpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='First_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='Last_Name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
