# Generated by Django 5.0.2 on 2024-03-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_register_first_name_register_last_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='myapp_register',
        ),
    ]
