# Generated by Django 5.0.4 on 2024-04-25 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=100)),
                ('students', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('starttiming', models.TimeField()),
                ('endtiming', models.TimeField()),
                ('Datee', models.DateField(default=datetime.date.today)),
                ('Durations', models.DurationField(default=datetime.timedelta(seconds=3600))),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
    ]
