# Generated by Django 5.0.2 on 2024-03-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=100)),
                ('students', models.IntegerField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('timing', models.TimeField()),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
    ]
