# Generated by Django 5.0.2 on 2024-03-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='students',
            field=models.IntegerField(),
        ),
    ]
