# Generated by Django 5.0.2 on 2024-03-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_booking_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='meeting',
        ),
    ]
